### ISSUE TITLE
[Zenfone 5] Crash on startup

### ISSUE THREAD

**Issue by E1iminate** [mortenpi/ebookdroid#2]
If app is not used to open a file, then it crashes on Zenfone 5 with "Application error" message. Tested on Android 4.4 and 5.0.

System:
Zenfone 5, Intel Atom

**Comment by mortenpi** [comment]
Sorry, I'm not a developer of this app, I just cloned the repo some years ago and it's very outdated. If you have issues with the latest version of the app you should probably report it to the actual devs: https://code.google.com/archive/p/ebookdroid/
